services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z
    command: server --address :9000 --console-address :9090 /data
    healthcheck:
      test: "mc ready local"
      start_period: 1s
      interval: 5s
      timeout: 15s
      retries: 10
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    restart: always
